Added test to check unrecognized options to parse().
libwww-perl/HTML-Form pull request #46
Opened 2022-10-06 16:21 UTC by manwar

Hi @oalders 

Please review the pull request.
It received the distribution as my Pull Request Club assignment for October.
I hope it counts towards my Hacktoberfest entry for year 2022.

Many Thanks.

Best Regards,
Mohammad

2022-10-06 16:41 UTC, oalders commented on t/form-parse.t
> +like( $warn[0], qr/^Unrecognized option foo in HTML::Form/ );
@haarg should we be using `Test::Warnings` here?

2022-10-07 02:47 UTC, oalders requested changes
Thank you so much for this, @manwar! Just a few comments. I think the only important one is regarding `Test::Warnings`. If you could squash it down to a single commit after your changes, that will make it a touch easier to merge.

Happy Hacktoberfest!

2022-10-07 02:47 UTC, oalders commented on t/form-parse.t
> +my @f = HTML::Form->parse( "", base => "http://localhost/", foo => 1 );
```suggestion
my @f = HTML::Form->parse( q{}, base => 'http://localhost/', foo => 1 );
```

2022-10-07 02:47 UTC, oalders commented on t/form-parse.t
> +use HTML::Form;
```suggestion
use HTML::Form ();
```

2022-10-07 02:47 UTC, oalders commented on t/form-parse.t
> +like( $warn[0], qr/^Unrecognized option foo in HTML::Form/ );
@manwar I think using `Test::Warnings` would be good here. I think we're standardizing on that.

2022-10-07 02:48 UTC, oalders commented
A `Changes` entry would also be helpful.

```
    - Added test to check unrecognized options to parse(). (GH#46) (Mohammad S Anwar)
```

2022-10-07 08:16 UTC, manwar commented
> A `Changes` entry would also be helpful.
> 
> ```
>     - Added test to check unrecognized options to parse(). (GH#46) (Mohammad S Anwar)
> ```

@oalders I have made all changes as suggested and also squashed into just one commit. 
Please review again.

2022-10-07 11:01 UTC, oalders approved these changes
Wonderful. Thanks, @manwar!

2022-10-07 11:26 UTC, merged